### PR TITLE
added super search install function

### PR DESCRIPTION
**Pull request by vabruzzo**
Hi,

I am sharpening my Python skills and found this project of yours. I wanted to see if I could add a super-search-install function to allow users to install packages by package number after a search. Rather than adding it to the super-search function I added it as a separate function. Let me know what you think, even if you don't want to pull. Nice job on burgaur by the way! It's the perfect amount of AUR automation.

-Vince

### CODE REVIEW

**Comment by vabruzzo** [comment]
Okay, wasn't sure if it was a good idea to leave SS documentation there since it does that, plus the extra step.

**Comment by thiagokokada** [comment]
Ok, made some comments about the code.

Don't know if I would like to accept this the way it currently is. Not that I didn't like the idea, but it would be better to avoid duplication of code, so maybe I need to rewrite `super_search` function so we could create something like `search_install` that depends on `super_search`.

**Comment by thiagokokada** [comment]
Just to explain: it would be better to have a function that returned the searched packages as a list or something like this, so you wouldn't need to do all the `subprocess` part again.

**Comment by vabruzzo** [comment]
Okay, thanks a lot for the feedback! Quite a helpful learning experience.

I understand what you're saying about the duplicate code. If you did incorporate something like this, you would want the user to have the search option and the search_install option, right? Rather than having a default search option that always gives the option to install results?

**Comment by thiagokokada** [comment]
@vga- I didn't quite understand your question, but I don't have any problem with a separate option to just search and search_install. The problem is just duplication of code, so I would prefer a rewrite of super_search first that just returned a list of package. After that, we would create a new super_search that called this function and your search_install.

**Comment by vabruzzo** [comment]
My question was whether or not you want two separate burgaur commands: one to simply return search results, and another to return search results with the option to install one or more of them. For example, yaourt only has one search function and by default the user has the option to install results if they want to.

So, if you wanted to remove duplicate could you could incorporate the option to install results into a single search command.

The other option that you suggest is to have three functions, correct? One search function that returns a list of packages, a second super_search function that calls the first function and prints the list for the user, and a third search_install function that calls the first functions, prints the numbered list to the screen, and gives the user the option to install any of the numbered packages.

**Comment by thiagokokada** [comment]
@vga- Actually, I think the separated commands are better since it would be faster to typing. For example:

```
$ burgaur --super-search --install package # or any other thing, the problem is that I would need to add another option to get the alternative behavior
vs.
$ burgaur --search-install package
```

I would just rename `--super-search-install` to `--search-install` because I think the first is too verbose (and I want to maintain two letters for the short version of the command for consistency).

My problem is only duplication of source code, since if I find a bug I would need to fix in it in two separate parts of the code, and code duplication is the root of all bugs®.

No, my idea is to have only the two options above. **In the code** we would have three different functions, the first one to make the search and return a list of packages, the second one to print them to terminal, and the third one to print them to terminal (with numbers) and allow user to install them as he wish. Since the first function don't present anything to the user it doesn't make sense to expose them in the UI too.

The first function would be generic enough that we could use for other things, just like the `make_install` function.

Hope it's clearly now.

**Comment by vabruzzo** [comment]
Yes that was clear. I apologize for any confusion.

I have removed the duplicate code, changed the string concatenations to str.format(), changed super_search_install to search_install, and -ssi to -si. 

One thing I did not change was the regex. I am not sure how to pull the package name out of the longer string otherwise. Is there a preferred python method? I have to pull out the string that begins 9 characters in and terminates at the first space.

Thanks again for the help and suggestions. I am a beginner and this has been more helpful than many pages in a book could have been.

**Comment by vabruzzo** [comment]
Good idea. I added a BOLDMAGENTA constant. This is the same constant that cower uses for that formatting code.

**Comment by vabruzzo** [comment]
I added a font color dictionary.

The only reason I formatted part of the text is so that the output of this new search_install command is exactly the same as the per-existing super_search command. Cower itself spits out the formatting code, so the regular burgaur -ss command already spits out the formatting code if the command is piped to a text file or something like that. This issue is not unique to the new search_install command.

On the plus side, cower already resets the terminal formatting, so there is no need to worry about that.

**Comment by vabruzzo** [comment]
For example, `cower -s` piped to a text file includes the ugly formatting code. And I don't have the C chops to fix it there :/

**Comment by thiagokokada** [comment]
Yeah, I know cower doesn't spit formatting code if it's piped or if we explicit disable it (using `--color=never` or `--quiet`), but the problem that I said is if someone is using burgaur in a script, so we need to consider that too. This wasn't a problem when we redirect the output from cower, but now that we print with formatting ourselves we need to thing about this corner cases too.

Anyway, I will review the code tomorrow, test it in my machine and probably merge this with some modifications.

**Comment by vabruzzo** [comment]
I did not take into consideration cower's color configuration options. Right now my code does not work well with color=auto. Basically, since I'm piping the output of the command, it does not output the color codes even though it should. Don't worry about testing it yet, I'm going to try to fix that problem. You can close this pull request and I'll submit another if I can work it out

**Comment by thiagokokada** [comment]
The best approach to resolve this problem is to pass `--color=never` to cower when you're creating the subprocess.

And after some tought, you can remove the regex by passing `--quiet` or `--format=` to cower. Using `--quiet` would strip the descriptions, that isn't what we would like, so probably is better to use something like `--format=%n+%v+%o+%d\n` (this will print each package as `package1+v1.0.0+132+package description\n`, a format that is really easy to parse using `str.split("+")`).

After searching and splitting, you can put everything in a list of dicts, something like `[{"package_name":"package1", "version":"v1.0.0", "votes":"132", "package_description":"package description"},{"package_name":"package2", "version":"v2.0.0", "votes":"97", "package_description":"package description 2"}]`. Actually, maybe would be better to include everything that cower can provide to us (see `Formatting` in `man cower` for details), so we could use that information latter. And maybe `+` is not the best separator (if a package description contains + in it, this would be a problem). Maybe `&&`?

For now, I am thinking it would be better to remove any string formatting from this PR. This is because I think string formatting in burgaur is really inconsistent now: if we are using external programs (like `makepkg` and `cower`), we generally print with color output, but any internal strings generated by the program does not have any string formatting. So it's better to not format any string for now. I will create a issue to implement string formatting in burgaur.

**Comment by thiagokokada** [comment]
I am closing this PR since in commit 1aae27ea I implemented something similar. I really liked your idea, but the issues with the original implementation was never solved so I decided to do it on my own. Thanks anyway.

**Pull request closed without merging**
