### PR TITLE
Add bash completion for long options and package names

### PR DESCRIPTION
**Pull request by damag**
The one thing I miss in burgaur that cower has is the bash completion for package names, so this PR adds it in.

I'm pretty much doing the same as cower's tab completion:
--force-update completes with all the foreign packages installed
--make-install and --search-install completes with an AUR search using cower

### CODE REVIEW

**Comment by thiagokokada** [comment]
Looks good.

**Comment by damag** [comment]
Thanks for merging it. When do you think you will make the next release?

**Comment by thiagokokada** [comment]
@damag Just put a new release (2.3) in AUR: https://aur.archlinux.org/packages/burgaur/

This release should also bring some refactorings and a surprising performance improvement (I removed a check that nowadays is useless and this does seems to make burgaur more responsive). Enjoy.

I have to say though, burgaur is mostly in maintance mode since I myself doesn't use it anymore (migrated to https://github.com/Jguer/yay). If cower breaks something this will eventually be deprecated.

**Comment by damag** [comment]
Great, thanks for the release.

Yay seems nice also, I'll have to check it out, thanks for the tip.

**Pull request merged**
